define(function () {
    var CODE = {
    	//性别码
        XBM: [
            {
                value:"0",
                text:"未知的性别"
            },
            {
                value:"1",
                text:"男性"
            },
            {
                value:"2",
                text:"女性"
            },
            {
                value:"9",
                text:"未说明的性别"
            }
        ],
        //学历码
        XLM: [
            {
                value:"10",
                text:"研究生教育"
            },
            {
                value:"11",
                text:"博士研究生毕业"
            },
            {
                value:"12",
                text:"博士研究生结业"
            },
            {
                value:"13",
                text:"博士研究生肄业"
            },
            {
                value:"14",
                text:"硕士研究生毕业"
            },
            {
                value:"15",
                text:"硕士研究生结业"
            },
            {
                value:"16",
                text:"硕士研究生肄业"
            },
            {
                value:"17",
                text:"研究生班毕业"
            },
            {
                value:"18",
                text:"研究生班结业"
            },
            {
                value:"19",
                text:"研究生班肄业"
            },
            {
                value:"20",
                text:"大学本科教育"
            },
            {
                value:"21",
                text:"大学本科毕业"
            },
            {
                value:"22",
                text:"大学本科结业"
            },
            {
                value:"23",
                text:"大学本科肄业"
            },
            {
                value:"28",
                text:"大学普通班毕业"
            },
            {
                value:"30",
                text:"大学专科教育"
            },
            {
                value:"31",
                text:"大学专科毕业"
            },
            {
                value:"32",
                text:"大学专科结业"
            },
            {
                value:"33",
                text:"大学专科肄业"
            },
            {
                value:"40",
                text:"中等职业教育"
            },
            {
                value:"41",
                text:"中等专科毕业"
            },
            {
                value:"42",
                text:"中等专科结业"
            },
            {
                value:"43",
                text:"中等专科肄业"
            },
            {
                value:"44",
                text:"职业高中毕业"
            },
            {
                value:"45",
                text:"职业高中结业"
            },
            {
                value:"46",
                text:"职业高中肄业"
            },
            {
                value:"47",
                text:"技工学校毕业"
            },
            {
                value:"48",
                text:"技工学校结业"
            },
            {
                value:"49",
                text:"技工学校肄业"
            },
            {
                value:"60",
                text:"普通高级中学教育"
            },
            {
                value:"61",
                text:"普通高中毕业"
            },
            {
                value:"62",
                text:"普通高中结业"
            },
            {
                value:"63",
                text:"普通高中肄业"
            },
            {
                value:"70",
                text:"初级中学教育"
            },
            {
                value:"71",
                text:"初中毕业"
            },
            {
                value:"73",
                text:"初中肄业"
            },
            {
                value:"80",
                text:"小学教育"
            },
            {
                value:"81",
                text:"小学毕业"
            },
            {
                value:"83",
                text:"小学肄业"
            },
            {
                value:"90",
                text:"其他"
            }

        ],
        //学位码
        XWM: [
            {
                value:"1",
                text:"名誉博士"
            },
            {
                value:"2",
                text:"博士"
            },
            {
                value:"201",
                text:"哲学博士学位"
            },
            {
                value:"202",
                text:"经济学博士学位"
            },
            {
                value:"203",
                text:"法学博士学位"
            },
            {
                value:"204",
                text:"教育学博士学位"
            },
            {
                value:"205",
                text:"文学博士学位"
            },
            {
                value:"206",
                text:"历史学博士学位"
            },
            {
                value:"207",
                text:"理学博士学位"
            },
            {
                value:"208",
                text:"工学博士学位"
            },
            {
                value:"209",
                text:"农学博士学位"
            },
            {
                value:"210",
                text:"医学博士学位"
            },
            {
                value:"211",
                text:"军事学博士学位"
            },
            {
                value:"212",
                text:"管理学博士学位"
            },
            {
                value:"245",
                text:"临床医学博士专业学位"
            },
            {
                value:"248",
                text:"兽医博士专业学位"
            },
            {
                value:"250",
                text:"口腔医学博士专业学位"
            },
            {
                value:"3",
                text:"硕士"
            },
            {
                value:"301",
                text:"哲学硕士学位"
            },
            {
                value:"302",
                text:"经济学硕士学位"
            },
            {
                value:"303",
                text:"法学硕士学位"
            },
            {
                value:"304",
                text:"教育学硕士学位"
            },
            {
                value:"305",
                text:"文学硕士学位"
            },
            {
                value:"306",
                text:"历史学硕士学位"
            },
            {
                value:"307",
                text:"理学硕士学位"
            },
            {
                value:"308",
                text:"工学硕士学位"
            },
            {
                value:"309",
                text:"农学硕士学位"
            },
            {
                value:"310",
                text:"医学硕士学位"
            },
            {
                value:"311",
                text:"军事学硕士学位"
            },
            {
                value:"312",
                text:"管理学硕士学位"
            },
            {
                value:"341",
                text:"法律硕士专业学位"
            },
            {
                value:"342",
                text:"教育硕士专业学位"
            },
            {
                value:"343",
                text:"工程硕士专业学位"
            },
            {
                value:"344",
                text:"建筑学硕士专业学位"
            },
            {
                value:"345",
                text:"临床学硕士专业学位"
            },
            {
                value:"346",
                text:"工商管理硕士专业学位"
            },
            {
                value:"347",
                text:"农业推广硕士专业学位"
            },
            {
                value:"348",
                text:"兽医硕士专业学位"
            },
            {
                value:"349",
                text:"公共管理硕士专业学位"
            },
            {
                value:"350",
                text:"口腔医学硕士专业学位"
            }
            ,
            {
                value:"351",
                text:"公共卫生硕士专业学位"
            }
            ,
            {
                value:"352",
                text:"军事硕士专业学位"
            }
            ,
            {
                value:"4",
                text:"学士"
            }
            ,
            {
                value:"401",
                text:"哲学学士学位"
            }
            ,
            {
                value:"402",
                text:"经济学学士学位"
            }
            ,
            {
                value:"403",
                text:"法学学士学位"
            }
            ,
            {
                value:"404",
                text:"教育学学士学位"
            }
            ,
            {
                value:"405",
                text:"文学学士学位"
            }
            ,
            {
                value:"406",
                text:"历史学学士学位"
            }
            ,
            {
                value:"407",
                text:"理学学士学位"
            }
            ,
            {
                value:"408",
                text:"工学学士学位"
            }
            ,
            {
                value:"409",
                text:"农学学士学位"
            },
            {
                value:"410",
                text:"医学学士学位"
            },
            {
                value:"411",
                text:"军事学学士学位"
            },
            {
                value:"412",
                text:"管理学学士学位"
            },
            {
                value:"444",
                text:"建筑学学士专业学位"
            }
        ],
        //岗位职业码
        GWZYM: [
            {
                value:"10",
                text:"教师"
            },
            {
                value:"20",
                text:"教师兼行政"
            },
            {
                value:"21",
                text:"教研室主任（组长）"
            },
            {
                value:"22",
                text:"年级主任（组长）"
            },
            {
                value:"23",
                text:"班主任"
            },
            {
                value:"24",
                text:"辅导员、教练员"
            },
            {
                value:"25",
                text:"共青团工作负责人"
            },
            {
                value:"26",
                text:"工会工作负责人"
            },
            {
                value:"27",
                text:"妇女工作负责人"
            },
            {
                value:"28",
                text:"其他工作负责人"
            },
            {
                value:"30",
                text:"行政"
            },
            {
                value:"64",
                text:"建筑维护与管理"
            },
            {
                value:"31",
                text:"校领导"
            },
            {
                value:"32",
                text:"行政处室负责人"
            },
            {
                value:"33",
                text:"行政处室工作"
            },
            {
                value:"34",
                text:"行政兼教学工作"
            },
            {
                value:"40",
                text:"教辅"
            },
            {
                value:"41",
                text:"实习实验工作与管理"
            },
            {
                value:"42",
                text:"教学仪器设备维护与管理"
            },
            {
                value:"43",
                text:"体育设备设施维护与管理"
            },
            {
                value:"44",
                text:"文艺设备设施维护与管理"
            },
            {
                value:"45",
                text:"图书教材工作与管理"
            },
            {
                value:"46",
                text:"档案资料工作与管理"
            },
            {
                value:"47",
                text:"电教设备维护与管理"
            },
            {
                value:"48",
                text:"宣传教育工作与管理"
            },
            {
                value:"49",
                text:"教辅兼教学工作"
            },
            {
                value:"60",
                text:"工勤"
            },
            {
                value:"61",
                text:"医护保健工作与管理"
            },
            {
                value:"62",
                text:"财务统计工作与管理"
            },
            {
                value:"63",
                text:"校园维护与管理"
            },
            {
                value:"65",
                text:"餐饮服务与管理"
            },
            {
                value:"66",
                text:"生活服务与管理"
            },
            {
                value:"67",
                text:"商贸服务与管理"
            },
            {
                value:"68",
                text:"教学服务与管理"
            },
            {
                value:"70",
                text:"校办企业"
            },
            {
                value:"71",
                text:"校办企业负责人"
            },
            {
                value:"79",
                text:"校办企业职工"
            },
            {
                value:"80",
                text:"其他工作"
            }

        ],
        //政治面貌码
        ZZMMM: [
            {
                value:"01",
                text:"中国共产党党员"
            },
            {
                value:"02",
                text:"中国共产党预备党员"
            },
            {
                value:"03",
                text:"中国共产主义青年团团员"
            },
            {
                value:"04",
                text:"中国国民党革命委员会会员"
            },
            {
                value:"05",
                text:"中国民主同盟盟员"
            },
            {
                value:"06",
                text:"中国民主建国会会员"
            },
            {
                value:"07",
                text:"中国民主促进会会员"
            },
            {
                value:"08",
                text:"中国农工民主党党员"
            },
            {
                value:"09",
                text:"中国致公党党员"
            },
            {
                value:"10",
                text:"九三学社社员"
            },
            {
                value:"11",
                text:"台湾民主自治同盟盟员"
            },
            {
                value:"12",
                text:"无党派民主人士"
            },
            {
                value:"13",
                text:"群众"
            }

        ],
        //学校主教学语言码
        ZJXYYM: [
        	{"value":"0","text":"无","zmCode":"wu"},
            {"value":"211","text":"汉语（中文）","zmCode":"zh"},
            {"value":"61","text":"俄语","zmCode":"ru"},
            {"value":"111","text":"塔吉克语","zmCode":"tg"},
            {"value":"161","text":"塔塔尔语","zmCode":"tt"},
            {"value":"162","text":"柯尔克孜语","zmCode":"ky"},
            {"value":"163","text":"哈萨克语","zmCode":"kk"},
            {"value":"168","text":"乌孜别克语","zmCode":"uz"},
            {"value":"212","text":"傣语","zmCode":"th"},
            {"value":"215","text":"藏语","zmCode":"bo"},
            {"value":"217","text":"朝鲜语","zmCode":"hn"},
            {"value":"222","text":"蒙古语","zmCode":"mn"},
            {"value":"223","text":"维吾尔语","zmCode":"ug"},
            {"value":"224","text":"壮语","zmCode":"za"},
            {"value":"501","text":"裕固语","zmCode":"yg"},
            {"value":"506","text":"保安语","zmCode":"bk"},
            {"value":"507","text":"达斡尔语","zmCode":"du"},
            {"value":"508","text":"东乡语","zmCode":"dx"},
            {"value":"509","text":"土语","zmCode":"tu"},
            {"value":"513","text":"鄂伦春语","zmCode":"ol"},
            {"value":"514","text":"鄂温克语","zmCode":"ew"},
            {"value":"517","text":"赫哲语","zmCode":"hz"},
            {"value":"518","text":"满语","zmCode":"me"},
            {"value":"519","text":"锡伯语","zmCode":"xb"},
            {"value":"524","text":"撒拉语","zmCode":"sh"},
            {"value":"531","text":"瑶语","zmCode":"ya"},
            {"value":"532","text":"仡佬语","zmCode":"ge"},
            {"value":"533","text":"京语","zmCode":"gi"},
            {"value":"536","text":"阿昌语","zmCode":"ac"},
            {"value":"537","text":"独龙语","zmCode":"dr"},
            {"value":"538","text":"基诺语","zmCode":"jn"},
            {"value":"539","text":"珞巴语","zmCode":"lb"},
            {"value":"540","text":"门巴语","zmCode":"mb"},
            {"value":"541","text":"怒语","zmCode":"nu"},
            {"value":"542","text":"普米语","zmCode":"pm"},
            {"value":"543","text":"羌语","zmCode":"qi"},
            {"value":"544","text":"土家语","zmCode":"tj"},
            {"value":"548","text":"景颇语","zmCode":"jp"},
            {"value":"551","text":"白语","zmCode":"bi"},
            {"value":"552","text":"哈尼语","zmCode":"ho"},
            {"value":"553","text":"拉祜语","zmCode":"lh"},
            {"value":"554","text":"傈僳语","zmCode":"ls"},
            {"value":"555","text":"纳西语","zmCode":"nx"},
            {"value":"556","text":"彝语","zmCode":"yi"},
            {"value":"563","text":"黎语","zmCode":"li"},
            {"value":"567","text":"侗语","zmCode":"do"},
            {"value":"568","text":"仫佬语","zmCode":"mm"},
            {"value":"569","text":"毛难语","zmCode":"mu"},
            {"value":"570","text":"水语","zmCode":"sy"},
            {"value":"574","text":"布依语","zmCode":"by"},
            {"value":"580","text":"苗语","zmCode":"mh"},
            {"value":"584","text":"崩龙语","zmCode":"bb"},
            {"value":"585","text":"布朗语","zmCode":"bl"},
            {"value":"586","text":"佤语","zmCode":"va"},
            {"value":"590","text":"高山语","zmCode":"gs"}
        ],
  		//班级类型代码
  		BJLXM : [
  			{"value":"10","text":"普通小学班"},
  			{"value":"11","text":"少数民族小学班"},
  			{"value":"12","text":"小学复式班"},
  			{"value":"13","text":"小学教学点班"},
  			{"value":"14","text":"小学特长班（文体艺智等班）"},
  			{"value":"15","text":"小学视力残疾班"},
  			{"value":"16","text":"小学听力残疾班"},
  			{"value":"17","text":"小学智力残疾班"},
  			{"value":"20","text":"普通初中班"},
  			{"value":"21","text":"少数民族初中班"},
  			{"value":"22","text":"初中复式班"},
  			{"value":"23","text":"初中教学点班"},
  			{"value":"24","text":"初中特长班（文体艺智等班）"},
  			{"value":"25","text":"初中视力残疾班"},
  			{"value":"26","text":"初中听力残疾班"},
  			{"value":"27","text":"初中智力残疾班"},
  			{"value":"40","text":"普通高中班"},
  			{"value":"41","text":"少数民族高中班"},
  			{"value":"42","text":"高中特长班（文体艺智等班）"}
  		],
  		//中小学课程代码
  		ZXXKC : [
  			{"value":"11","text":"品德与生活（社会）"},
  			{"value":"12","text":"思想品德（政治）"},
  			{"value":"13","text":"语文"},
  			{"value":"14","text":"数学"},
  			{"value":"15","text":"科学"},
  			{"value":"16","text":"物理"},
  			{"value":"17","text":"化学"},
  			{"value":"18","text":"生物"},
  			{"value":"19","text":"历史与社会"},
  			{"value":"20","text":"地理"},
  			{"value":"21","text":"历史"},
  			{"value":"22","text":"体育与健康"},
  			{"value":"23","text":"艺术"},
  			{"value":"24","text":"音乐"},
  			{"value":"25","text":"美术"},
  			{"value":"26","text":"信息技术"},
  			{"value":"27","text":"通用技术"},
  			{"value":"40","text":"外语"},
  			{"value":"41","text":"英语"},
  			{"value":"42","text":"日语"},
  			{"value":"43","text":"俄语"},
  			{"value":"49","text":"其他外国语"},
  			{"value":"60","text":"综合实践活动"},
  			{"value":"61","text":"信息技术"},
  			{"value":"62","text":"劳动与技术"}
  		],
  		//中小学课程等级代码表
  		ZXXKCDJ :[
  			{"value":"1","text":"国家课程"},
  			{"value":"2","text":"地方课程"},
  			{"value":"3","text":"校本课程"}
  		],
  		//授课方式代码
  		SKFS : [
  			{"value":"1","text":"面授讲课"},
  			{"value":"2","text":"辅导"},
  			{"value":"3","text":"录像讲课"},
  			{"value":"4","text":"网络教学"},
  			{"value":"5","text":"实验"},
  			{"value":"6","text":"实习"},
  			{"value":"9","text":"其他"}
  		],
  		//年级代码表
  		NJ : [
  			{"value":"1","text":"一年级"},
  			{"value":"2","text":"二年级"},
  			{"value":"3","text":"三年级"},
  			{"value":"4","text":"三年级及以上"},
  			{"value":"5","text":"四年级"},
  			{"value":"8","text":"四年级及以上"},
  			{"value":"6","text":"五年级"},
  			{"value":"7","text":"五年级及以上"},
  			{"value":"9","text":"六年级"},
  			{"value":"10","text":"六年级及以上"}
  		],
  		//学期代码
  		XQ : [
  			{"value":"1","text":"秋季学期"},
  			{"value":"1","text":"春季学期"},
  			{"value":"1","text":"夏季学期"},
  			{"value":"1","text":"其他"}
  		],
  		//考试方式码
  		KSFS :[
  			{"value":"1","text":"笔试"},
  			{"value":"2","text":"口试"},
  			{"value":"3","text":"面试"},
  			{"value":"4","text":"操作"},
  			{"value":"5","text":"机考"},
  			{"value":"6","text":"大作业"},
  			{"value":"7","text":"实验报告"},
  			{"value":"8","text":"其他"}
  		],
        //港澳台侨外码
        GATQWM:[
            {"value":"1","text":"中国"},
            {"value":"2","text":"香港"},
            {"value":"3","text":"澳门"},
            {"value":"4","text":"台湾"},
            {"value":"5","text":"其它"}
        ],
        //政治面貌码
        ZZMMM:[
            {"value":"1","text":"中共党员"},
            {"value":"2","text":"中共预备党员"},
            {"value":"3","text":"共青团员"},
            {"value":"4","text":"民革党员"},
            {"value":"5","text":"民盟党员"},
            {"value":"6","text":"民建会员"},
            {"value":"7","text":"民进会员"},
            {"value":"8","text":"农工党党员"},
            {"value":"9","text":"致公党党员"},
            {"value":"10","text":"九三学社社员"},
            {"value":"11","text":"台盟盟员"},
            {"value":"12","text":"无党派民主人士"},
            {"value":"13","text":"普通公民"}
        ],
        //健康状况码
        JKZKM:[
            {"value":"1","text":"健康"},
            {"value":"2","text":"一般"},
            {"value":"3","text":"较差"}
        ],
        //信仰宗教码
        XYZJM:[
            {"value":"1","text":"佛教"},
            {"value":"2","text":"伊斯兰教"},
            {"value":"3","text":"天主教"},
            {"value":"4","text":"基督教"},
            {"value":"5","text":"道教"},
            {"value":"6","text":"萨满教"},
            {"value":"7","text":"东正教"},
            {"value":"8","text":"东巴教"},
            {"value":"9","text":"伊斯兰教"},
            {"value":"10","text":"藏传佛教"},
            {"value":"11","text":"小乘佛教"}
        ],
        //血型码
        XXM:[
            {"value":"1","text":"A"},
            {"value":"2","text":"B"},
            {"value":"3","text":"O"},
            {"value":"4","text":"AB"}
        ],
        //学历码
        XLM:[
            {"value":"1","text":"小学"},
            {"value":"2","text":"初中"},
            {"value":"3","text":"高中"},
            {"value":"4","text":"初中中专"},
            {"value":"5","text":"高中中专"},
            {"value":"6","text":"大专"},
            {"value":"7","text":"本科"},
            {"value":"8","text":"硕士研究生"},
            {"value":"9","text":"博士研究生"}
        ],
        //证件类型
        ZJLXM:[
            {"value":"1","text":"居民身份证"},
            {"value":"2","text":"军官证"},
            {"value":"3","text":"士兵证"},
            {"value":"4","text":"文职干部证"},
            {"value":"5","text":"部队离退休证"},
            {"value":"6","text":"香港特区护照/身份证明"},
            {"value":"7","text":"澳门特区护照/身份证明"},
            {"value":"8","text":"台湾居民来往大陆通行证"},
            {"value":"9","text":"境外永久居住证"},
            {"value":"10","text":"护照"},
            {"value":"11","text":"户口薄"},
            {"value":"12","text":"其它"}

        ],
        //级别代码
        TGJSJHLX:[
            {"value":"1","text":"国家级"},
            {"value":"2","text":"教育部"},
            {"value":"3","text":"中央其他部委"},
            {"value":"4","text":"省（自治区、直辖市）级"},
            {"value":"5","text":"省级教育行政部门"},
            {"value":"6","text":"省级其他部门"},
            {"value":"7","text":"地（市、州）级"},
            {"value":"8","text":"地级教育行政部门"},
            {"value":"9","text":"地级其他部门"},
            {"value":"10","text":"县级"},
            {"value":"11","text":"县级教育行政部门"},
            {"value":"12","text":"县级其他部门"},
            {"value":"13","text":"乡（镇）级"},
            {"value":"14","text":"国际"},
            {"value":"15","text":"其他"}
        ],
       //职务级别码
		ZWJBM : [
  			{"value":"101","text":"国家级正职"},
  			{"value":"102","text":"国家级副职"},
  			{"value":"111","text":"省部级正职"},
  			{"value":"112","text":"省部级副职"},
  			{"value":"121","text":"厅局级正职"},
  			{"value":"122","text":"厅局级副职"},
  			{"value":"131","text":"县处级正职"},
  			{"value":"132","text":"县处级副职"},
  			{"value":"141","text":"乡科级正职"},
  			{"value":"142","text":"乡科级副职"},
  			{"value":"150","text":"科员级"},
  			{"value":"160","text":"办事员级"},
  			{"value":"199","text":"未定职公务员"},
  			{"value":"211","text":"一级职员"},
  			{"value":"212","text":"二级职员"},
  			{"value":"221","text":"三级职员"},
  			{"value":"222","text":"四级职员"},
  			{"value":"231","text":"五级职员"},
  			{"value":"232","text":"六级职员"},
  			{"value":"241","text":"七级职员"},
  			{"value":"242","text":"八级职员"},
  			{"value":"250","text":"九级职员"},
  			{"value":"260","text":"十级职员"},
  			{"value":"299","text":"未定级职员"},
  			{"value":"410","text":"高级"},
  			{"value":"411","text":"正高级"},
  			{"value":"412","text":"副高级"},
  			{"value":"420","text":"初级"},
  			{"value":"434","text":"助理级"},
  			{"value":"435","text":"员级"},
  			{"value":"499","text":"未定职级专业技术人员"}
  		],
       //民族码
		MZM:[
			{"value":"01","text":"汉族"},
			{"value":"02","text":"蒙古族"},
			{"value":"03","text":"回族"},
			{"value":"04","text":"藏族"},
			{"value":"05","text":"维吾尔族"},
			{"value":"06","text":"苗族"},
			{"value":"07","text":"彝族"},
			{"value":"08","text":"壮族"},
			{"value":"09","text":"布依族"},
			{"value":"10","text":"朝鲜族"},
			{"value":"11","text":"满族"},
			{"value":"12","text":"侗族"},
			{"value":"13","text":"瑶族"},
			{"value":"14","text":"白族"},
			{"value":"15","text":"土家族"},
			{"value":"16","text":"哈尼族"},
			{"value":"17","text":"哈萨克族"},
			{"value":"18","text":"傣族"},
			{"value":"19","text":"黎族"},
			{"value":"20","text":"傈僳族"},
			{"value":"21","text":"佤族"},
			{"value":"22","text":"畲族"},
			{"value":"23","text":"高山族"},
			{"value":"24","text":"拉祜族"},
			{"value":"25","text":"水族"},
			{"value":"26","text":"东乡族"},
			{"value":"27","text":"纳西族"},
			{"value":"28","text":"景颇族"},
			{"value":"29","text":"柯尔克孜族"},
			{"value":"30","text":"土族"},
			{"value":"31","text":"达斡尔族"},
			{"value":"32","text":"仫佬族"},
			{"value":"33","text":"羌族"},
			{"value":"34","text":"布朗族"},
			{"value":"35","text":"撒拉族"},
			{"value":"36","text":"毛难族"},
			{"value":"37","text":"仡佬族"},
			{"value":"38","text":"锡伯族"},
			{"value":"39","text":"阿昌族"},
			{"value":"40","text":"普米族"},
			{"value":"41","text":"塔吉克族"},
			{"value":"42","text":"怒族"},
			{"value":"43","text":"乌孜别克族"},
			{"value":"44","text":"俄罗斯族"},
			{"value":"45","text":"鄂温克族"},
			{"value":"46","text":"德昂族"},
			{"value":"47","text":"保安族"},
			{"value":"48","text":"裕固族"},
			{"value":"49","text":"京族"},
			{"value":"50","text":"塔塔尔族"},
			{"value":"51","text":"独龙族"},
			{"value":"52","text":"鄂伦春族"},
			{"value":"53","text":"赫哲族"},
			{"value":"54","text":"门巴族"},
			{"value":"55","text":"珞巴族"},
			{"value":"56","text":"基诺族"},
			{"value":"81","text":"穿青人族"},
			{"value":"97","text":"其他"},
			{"value":"98","text":"外国血统中国籍人士"}
		],
       //课程代码
        RZKM:[
            {"value":"1","text":"品德与生活（社会）"},
            {"value":"2","text":"思想品德（政治）"},
            {"value":"3","text":"语文"},
            {"value":"4","text":"数学"},
            {"value":"5","text":"科学"},
            {"value":"6","text":"物理"},
            {"value":"7","text":"化学"},
            {"value":"8","text":"生物"},
            {"value":"9","text":"历史与社会"},
            {"value":"10","text":"地理"},
            {"value":"11","text":"历史"},
            {"value":"12","text":"体育与健康"},
            {"value":"13","text":"艺术"},
            {"value":"14","text":"音乐"},
            {"value":"15","text":"美术"},
            {"value":"16","text":"信息技术"},
            {"value":"17","text":"通用技术"},
            {"value":"18","text":"英语"},
            {"value":"19","text":"日语"},
            {"value":"20","text":"俄语"},
            {"value":"21","text":"其他外国语"},
            {"value":"22","text":"信息技术"},
            {"value":"23","text":"劳动与技术"}
        ],
        //职务类别
		ZWLB : [
  			{"value":"11","text":"党委正职"},
  			{"value":"12","text":"行政正职"},
  			{"value":"13","text":"党的职能部门正职"},
  			{"value":"14","text":"行政职能部门正职"},
  			{"value":"15","text":"民主党派正职"},
  			{"value":"16","text":"社会团体正职"},
  			{"value":"21","text":"党委副职"},
  			{"value":"22","text":"行政副职"},
  			{"value":"23","text":"党的职能部门副职"},
  			{"value":"24","text":"行政职能部门副职"},
  			{"value":"25","text":"民主党派副职"},
  			{"value":"26","text":"社会团体副职"},
  			{"value":"31","text":"党委常委"},
  			{"value":"32","text":"党委委员"},
  			{"value":"33","text":"纪委委员"},
  			{"value":"34","text":"校长助理"},
  			{"value":"35","text":"总会计师"},
  			{"value":"36","text":"总经济师"},
  			{"value":"38","text":"党委其他职"},
  			{"value":"39","text":"行政其他职"},
  			{"value":"41","text":"党的职能部门其他职"},
  			{"value":"42","text":"行政职能部门其他职"},
  			{"value":"43","text":"民主党派其他职"},
  			{"value":"44","text":"社会团体其他职"}
  		],
  		//政治面貌异常类别
		YCLB : [
  			{"value":"01","text":"入团转党"},
  			{"value":"02","text":"重新入党"},
  			{"value":"11","text":"延期转正"},
  			{"value":"21","text":"未予登记"},
  			{"value":"22","text":"暂缓登记"},
  			{"value":"31","text":"自动脱党"},
  			{"value":"32","text":"除名"},
  			{"value":"33","text":"取消预备党员资格"},
  			{"value":"34","text":"开除党籍"},
  			{"value":"99","text":"其他"}
  		],
  		//教师来源
		JSLY : [
  			{"value":"10","text":"录用应届毕业生"},
  			{"value":"11","text":"应届本科生"},
  			{"value":"111","text":"本校应届本科生"},
  			{"value":"112","text":"外校应届本科生"},
  			{"value":"12","text":"应届硕士生"},
  			{"value":"121","text":"本校应届硕士生"},
  			{"value":"122","text":"外校应届本科生"},
  			{"value":"131","text":"本校应届博士生"},
  			{"value":"132","text":"外校应届博士生"},
  			{"value":"14","text":"国内博士后"},
  			{"value":"15","text":"国外博士/博士后"},
  			{"value":"16","text":"其他应届生"},
  			{"value":"20","text":"军队转业、复员"},
  			{"value":"21","text":"军转干部安置"},
  			{"value":"22","text":"复员军人安置"},
  			{"value":"31","text":"系统内高校调入"},
  			{"value":"32","text":"系统内其他单位调入"},
  			{"value":"321","text":"地方教育系统调入"},
  			{"value":"33","text":"系统外调入"},
  			{"value":"331","text":"中央其他部门调入"},
  			{"value":"332","text":"地方其他部门调入"},
  			{"value":"41","text":"院士"},
  			{"value":"42","text":"特聘教授"},
  			{"value":"43","text":"杰出人才"},
  			{"value":"44","text":"优秀人才"},
  			{"value":"45","text":"录用学成归国人员"},
  			{"value":"46","text":"其他引进人才"},
  			{"value":"49","text":"外国专家"},
  			{"value":"51","text":"社会招聘专业技术人员"},
  			{"value":"52","text":"其他社会招聘人员"},
  			{"value":"53","text":"社会招聘工勤人员"},
  			{"value":"99","text":"其他进校人员"}
  		],
  		//家庭关系
		JTGX : [
  			{"value":"01","text":"本人"},
  			{"value":"02","text":"户主"},
  			{"value":"10","text":"配偶"},
  			{"value":"11","text":"夫"},
  			{"value":"12","text":"妻"},
  			{"value":"20","text":"子"},
  			{"value":"21","text":"独生子"},
  			{"value":"22","text":"长子"},
  			{"value":"23","text":"次子"},
  			{"value":"24","text":"三子"},
  			{"value":"25","text":"四子"},
  			{"value":"26","text":"五子"},
  			{"value":"27","text":"养子或继子"},
  			{"value":"28","text":"女婿"},
  			{"value":"29","text":"其他子"},
  			{"value":"30","text":"女"},
  			{"value":"31","text":"独生女"},
  			{"value":"32","text":"长女"},
  			{"value":"33","text":"二女"},
  			{"value":"34","text":"三女"},
  			{"value":"35","text":"四女"},
  			{"value":"36","text":"五女"},
  			{"value":"37","text":"养女"},
  			{"value":"38","text":"儿媳"},
  			{"value":"39","text":"其他女儿"},
  			{"value":"40","text":"孙子、孙女或外孙子、外孙女"},
  			{"value":"41","text":"孙子"},
  			{"value":"42","text":"孙女"},
  			{"value":"43","text":"外孙子"},
  			{"value":"44","text":"外孙女"},
  			{"value":"45","text":"孙媳妇或外孙媳妇"},
  			{"value":"46","text":"孙女婿或外孙女婿"},
  			{"value":"47","text":"曾孙子或外曾孙子"},
  			{"value":"48","text":"曾孙女或外曾孙女"},
  			{"value":"49","text":"其他孙子、孙女或外孙子、外孙女"},
  			{"value":"50","text":"父母"},
  			{"value":"51","text":"父亲"},
  			{"value":"52","text":"母亲"},
  			{"value":"53","text":"公公"},
  			{"value":"54","text":"婆婆"},
  			{"value":"55","text":"岳父"},
  			{"value":"56","text":"岳母"},
  			{"value":"57","text":"继父或养父"},
  			{"value":"58","text":"继母或养母"},
  			{"value":"59","text":"其他父母关系"},
  			{"value":"60","text":"祖父母或外祖父母"},
  			{"value":"61","text":"祖父"},
  			{"value":"62","text":"祖母"},
  			{"value":"63","text":"外祖父"},
  			{"value":"64","text":"外祖母"},
  			{"value":"65","text":"配偶的祖父母或外祖父母"},
  			{"value":"66","text":"曾祖父"},
  			{"value":"67","text":"曾祖母"},
  			{"value":"68","text":"配偶的曾祖父母"},
  			{"value":"69","text":"其他祖父母或外祖父母关系"},
  			{"value":"70","text":"兄弟姐妹"},
  			{"value":"71","text":"兄"},
  			{"value":"72","text":"嫂"},
  			{"value":"73","text":"弟"},
  			{"value":"74","text":"弟媳"},
  			{"value":"75","text":"姐姐"},
  			{"value":"76","text":"姐夫"},
  			{"value":"77","text":"妹妹"},
  			{"value":"78","text":"妹夫"},
  			{"value":"79","text":"其他兄弟姐妹"},
  			{"value":"80","text":"其他"},
  			{"value":"97","text":"其他亲属"},
  			{"value":"99","text":"非亲属"}
  		],
  		//奖励级别
		JLJB : [
  			{"value":"10","text":"国家级"},
  			{"value":"20","text":"省、部委级"},
  			{"value":"21","text":"教育部"},
  			{"value":"22","text":"中央其他部委"},
  			{"value":"23","text":"省（自治区、直辖市）级"},
  			{"value":"30","text":"省部门级、地（市、州）级"},
  			{"value":"31","text":"省级教育行政部门"},
  			{"value":"32","text":"省级其他部门"},
  			{"value":"33","text":"地（市、州）级"},
  			{"value":"40","text":"地（市、州）部门级、县（区、旗）级"},
  			{"value":"41","text":"地级教育行政部门"},
  			{"value":"42","text":"地级其他部门"},
  			{"value":"43","text":"县级"},
  			{"value":"50","text":"县部门级、乡（镇）级"},
  			{"value":"51","text":"县级教育行政部门"},
  			{"value":"52","text":"县级其他部门"},
  			{"value":"53","text":"乡（镇）级"},
  			{"value":"60","text":"学校级"},
  			{"value":"70","text":"国际"},
  			{"value":"99","text":"其他"}
  		],
  		//奖励等级
		JLDJ : [
  			{"value":"1","text":"特等"},
  			{"value":"2","text":"一等"},
  			{"value":"3","text":"二等"},
  			{"value":"4","text":"三等"},
  			{"value":"5","text":"四等"},
  			{"value":"6","text":"未评等级"},
  			{"value":"9","text":"其他"}
  		],
        //批准单位级别码
        PZDWJBM:[
            {"value":"1","text":"中央、国家级（正）"},
            {"value":"2","text":"中央、国家级（副）"},
            {"value":"3","text":"省、部级"},
            {"value":"4","text":"副省、副部级"},
            {"value":"5","text":"地、厅、司、局级"},
            {"value":"6","text":"副地、副厅、副司、副局级"},
            {"value":"7","text":"县、处级"},
            {"value":"8","text":"副县、副处级"},
            {"value":"9","text":"乡、科级"},
            {"value":"10","text":"副乡、副科级"},
            {"value":"11","text":"股级"},
            {"value":"12","text":"大行政区（军政委员会）"},
            {"value":"13","text":"中央军委级"},
            {"value":"14","text":"解放军总部级"},
            {"value":"15","text":"大军区正级"},
            {"value":"16","text":"大军区副级"},
            {"value":"17","text":"正兵团级"},
            {"value":"18","text":"副兵团级"},
            {"value":"19","text":"正军级"},
            {"value":"20","text":"副军级"},
            {"value":"21","text":"正师级"},
            {"value":"22","text":"副师（正旅）级"},
            {"value":"23","text":"正团（副旅）级"},
            {"value":"24","text":"副团级"},
            {"value":"25","text":"正营级"},
            {"value":"26","text":"副营级"},
            {"value":"27","text":"正连级"},
            {"value":"28","text":"副连级"},
            {"value":"29","text":"排级"},
            {"value":"30","text":"班级"},
            {"value":"31","text":"国际组织、机构"},
            {"value":"32","text":"外国组织、机构"},
            {"value":"33","text":"无级别"},
            {"value":"34","text":"其他"}
        ],
        //专家类别代码表
        ZJLB:[
            {"value":"1","text":"中国科学院院士"},
            {"value":"2","text":"中国工程院院士"},
            {"value":"3","text":"两院院士"},
            {"value":"4","text":"外国科学院院士"},
            {"value":"5","text":"中国社会科学院学部委员"},
            {"value":"6","text":"国家主管部门批准的有突出贡献的专家"},
            {"value":"7","text":"享受政府特殊津贴（按月发放）专家"},
            {"value":"8","text":"享受政府特殊津贴（一次性发放）专家"},
            {"value":"9","text":"国家主管部门批准的其他专家"},
            {"value":"10","text":"省、部级有突出贡献专家"},
            {"value":"11","text":"地、市级有突出贡献专家"},
            {"value":"12","text":"县级有突出贡献专家"},
            {"value":"13","text":"全军有突出贡献专家"},
            {"value":"14","text":"大军区有突出贡献专家"},
            {"value":"15","text":"军级有突出贡献专家"},
            {"value":"16","text":"师级有突出贡献专家"},
            {"value":"17","text":"团级有突出贡献专家"},
            {"value":"18","text":"其他专家"}

        ],
        //教学类型码
        JXLXM:[
            {"value":"1","text":"讲课"},
            {"value":"2","text":"编写教材"},
            {"value":"3","text":"辅导"},
            {"value":"4","text":"带实验"},
            {"value":"5","text":"带实习"},
            {"value":"6","text":"带设计"},
            {"value":"7","text":"带社会实践"},
            {"value":"8","text":"指导论文"},
            {"value":"9","text":"带军训"},
            {"value":"10","text":"带学工"},
            {"value":"11","text":"带学农"},
            {"value":"12","text":"班主任"},
            {"value":"13","text":"指导员"},
            {"value":"14","text":"政治辅导员"},
            {"value":"15","text":"指导研究生"},
            {"value":"16","text":"其他"}
        ],
        //任课学段码
        RKXDM:[
            {"value":"1","text":"学前教育"},
            {"value":"2","text":"小学"},
            {"value":"3","text":"普通初中"},
            {"value":"4","text":"普通高中"},
            {"value":"5","text":"职业初中"},
            {"value":"6","text":"职业高中"},
            {"value":"7","text":"成人中等专业学校"},
            {"value":"8","text":"成人中学"},
            {"value":"9","text":"特殊教育"},
            {"value":"10","text":"其他"}
        ],
        //任课角色码
        RKJSM:[
            {"value":"1","text":"主讲"},
            {"value":"2","text":"辅导"},
            {"value":"3","text":"实验"},
            {"value":"4","text":"习题"},
            {"value":"5","text":"其他"}
        ],
        //保险福利费细目代码
        BXFLFM:[
            {"value":"01","text":"职工丧葬抚恤救济费"},
            {"value":"02","text":"职工生活困难补助"},
            {"value":"03","text":"职工计划生育补贴"},
            {"value":"11","text":"职工医疗卫生费"},
            {"value":"12","text":"职工文体宣传费"},
            {"value":"13","text":"职工集体福利事业补贴费"},
            {"value":"14","text":"职工集体福利设施费"},
            {"value":"16","text":"职工冬季取暖补贴"},
            {"value":"19","text":"职工个人其他保险福利费用"},
            {"value":"51","text":"职工集体保险福利其他费用"},
            {"value":"52","text":"离休金"},
            {"value":"53","text":"退休金"},
            {"value":"54","text":"退职生活费"},
            {"value":"55","text":"离退人员医疗卫生费"},
            {"value":"56","text":"护理费"},
            {"value":"57","text":"生活补贴"},
            {"value":"58","text":"离休人员交通费补贴"},
            {"value":"59","text":"离休人员丧葬抚恤救济费"},
            {"value":"60","text":"离休人员冬季取暖补贴"},
            {"value":"61","text":"离休人员物价补贴"},
            {"value":"99","text":"离休人员保险福利其他费用"}
        ],
        //工资类别码
        GZLBM:[
            {"value":"1","text":"行政机关"},
            {"value":"2","text":"公务员"},
            {"value":"3","text":"技术工人"},
            {"value":"4","text":"普通工人"},
            {"value":"5","text":"试用期公务员"},
            {"value":"6","text":"学徒期技术工人"},
            {"value":"7","text":"熟练期普通工人"},
            {"value":"8","text":"事业单位"},
            {"value":"9","text":"职员"},
            {"value":"10","text":"专业技术"},
            {"value":"11","text":"技术工人"},
            {"value":"12","text":"普通工人"},
            {"value":"13","text":"试用期行政管理人员"},
            {"value":"14","text":"见习期专业技术人员"},
            {"value":"15","text":"学徒期技术工人"},
            {"value":"16","text":"熟练期普通工人"},
            {"value":"17","text":"企业"},
            {"value":"18","text":"部队"},
            {"value":"19","text":"行员"},
            {"value":"20","text":"行员试用期"},
            {"value":"21","text":"运动员"},
            {"value":"22","text":"其他"}
        ],
        //工资变动原因码
        GZBDYYM:[
            {"value":"1","text":"职务晋升"},
            {"value":"2","text":"连续五年考核合格"},
            {"value":"3","text":"连续五年考核合格晋升一级"},
            {"value":"4","text":"连续五年考核合格倒级差"},
            {"value":"5","text":"连续三年考核优秀晋升一级"},
            {"value":"6","text":"连续三年考核优秀倒级差"},
            {"value":"7","text":"其他"}
        ],
        //变动后工资级别码
        BDHJBM:[
            {"value":"1","text":"一级"},
            {"value":"2","text":"二级"},
            {"value":"3","text":"三级"},
            {"value":"4","text":"四级"},
            {"value":"5","text":"五级"},
            {"value":"6","text":"六级"},
            {"value":"7","text":"七级"},
            {"value":"8","text":"八级"},
            {"value":"9","text":"九级"},
            {"value":"10","text":"十级"},
            {"value":"11","text":"十一级"},
            {"value":"12","text":"十二级"},
            {"value":"13","text":"十三级"},
            {"value":"14","text":"十四级"},
            {"value":"15","text":"十五级"},
            {"value":"16","text":"其他"}
        ],
        //学制码
        XZM: [
            {
                value:"1",
                text:"小学",
                years:"小学5年制"
            },
            {
                value:"2",
                text:"小学",
                years:"小学6年制"
            },
            {
                value:"3",
                text:"初中",
                years:"初中3年制"
            },
            {
                value:"4",
                text:"初中",
                years:"初中4年制"
            },
            {
                value:"5",
                text:"高中",
                years:"高中3年制"
            }
        ],
        //年级码
        NJM: [
            {
                value:"1",
                text:"一年级"
            },
            {
                value:"2",
                text:"二年级"
            },
            {
                value:"3",
                text:"三年级"
            },
            {
                value:"4",
                text:"四年级"
            },
            {
                value:"5",
                text:"五年级"
            },
            {
                value:"6",
                text:"六年级"
            },
            {
                value:"7",
                text:"七年级"
            },
            {
                value:"8",
                text:"八年级"
            },
            {
                value:"9",
                text:"九年级"
            },
            {
                value:"10",
                text:"高一年级"
            },
            {
                value:"11",
                text:"高二年级"
            },
            {
                value:"12",
                text:"高三年级"
            }
        ],
        //进修性质
        JXXZ:[
            {"value":"1","text":"培训"},
            {"value":"2","text":"进修"}
        ],
        //学习方式
        XXFS:[
            {"value":"1","text":"全脱产（离岗）"},
            {"value":"2","text":"半脱产（半离岗）"},
            {"value":"3","text":"不脱产（不离岗）"}
        ],
        //单位性质
        DWXZ:[
            {"value":"10","text":"机关"},
            {"value":"11","text":"省级以上党政机关"},
            {"value":"12","text":"省级以下党政机关"},
            {"value":"20","text":"事业单位"},
            {"value":"21","text":"科研设计单位"},
            {"value":"22","text":"高等学校"},
            {"value":"23","text":"其他教育单位"},
            {"value":"24","text":"医疗卫生单位"},
            {"value":"25","text":"体育文化单位"},
            {"value":"29","text":"其他事业单位"},
            {"value":"30","text":"企业"},
            {"value":"31","text":"国有企业"},
            {"value":"32","text":"中外合资企业"},
            {"value":"33","text":"民营（私营）企业"},
            {"value":"34","text":"外资企业"},
            {"value":"35","text":"集体企业"},
            {"value":"39","text":"其他企业"},
            {"value":"40","text":"部队"},
            {"value":"50","text":"社会组织机构"},
            {"value":"60","text":"国际组织机构"},
            {"value":"70","text":"国防科工机构"},
            {"value":"80","text":"财政金融机构"},
            {"value":"99","text":"其他"}
        ],
        //学术团体级别
        XSTTJB:[
            {"value":"1","text":"国际学术团体"},
            {"value":"2","text":"国家级学术团体"},
            {"value":"3","text":"省市、部委级学术团体"},
            {"value":"4","text":"地（市）级学术团体"},
            {"value":"5","text":"县（区、旗）级学术团体"}
        ],
        //辞职原因
        CZYY:[
            {"value":"1","text":"任职期满"},
            {"value":"2","text":"工作调动"},
            {"value":"3","text":"换届改选"},
            {"value":"4","text":"离退休"},
            {"value":"5","text":"健康原因"},
            {"value":"6","text":"辞职"},
            {"value":"7","text":"免职"},
            {"value":"8","text":"处分"},
            {"value":"9","text":"其他"}
        ],
        //离退休享受待遇
        LTXXSDY:[
            {"value":"1","text":"与离退前级别同等待遇"},
            {"value":"2","text":"享受上一级政治待遇"},
            {"value":"3","text":"享受上一级住房待遇"},
            {"value":"4","text":"享受上一级医疗待遇"},
            {"value":"5","text":"享受上一级用车待遇"},
            {"value":"6","text":"享受上一级政治、住房待遇"},
            {"value":"7","text":"享受上一级政治、医疗待遇"},
            {"value":"8","text":"享受上一级政治、用车待遇"},
            {"value":"9","text":"享受上一级住房、医疗待遇"},
            {"value":"A","text":"享受上一级住房、用车待遇"},
            {"value":"B","text":"享受上一级医疗、用车待遇"},
            {"value":"C","text":"享受上一级政治、住房、医疗待遇"},
            {"value":"D","text":"享受上一级政治、住房、用车待遇"},
            {"value":"E","text":"享受上一级政治、医疗、用车待遇"},
            {"value":"F","text":"享受上一级住房、医疗、用车待遇"},
            {"value":"G","text":"享受上一级政治、住房、医疗、用车待遇"}
        ],
        //离校离职原因
         LZYY:[
            {"value":"11","text":"离休"},
            {"value":"12","text":"退休"},
            {"value":"21","text":"系统内调出/调至其他高校"},
            {"value":"22","text":"调出至系统外"},
            {"value":"23","text":"调至系统内其他单位"},
            {"value":"31","text":"参军"},
            {"value":"32","text":"进修学习"},
            {"value":"41","text":"辞职"},
            {"value":"42","text":"辞退"},
            {"value":"43","text":"合同期满"},
            {"value":"51","text":"除名"},
            {"value":"52","text":"开除"},
            {"value":"53","text":"死亡"},
            {"value":"54","text":"失踪"},
            {"value":"55","text":"借调期满"},
            {"value":"56","text":"借调外出踪"},
            {"value":"99","text":"其他"}
        ],
        //死亡原因
         SWYY:[
            {"value":"40","text":"事故灾难致死"},
            {"value":"41","text":"溺水死亡"},
            {"value":"42","text":"交通事故致死"},
            {"value":"43","text":"拥挤踩踏致死"},
            {"value":"44","text":"房屋倒塌致死"},
            {"value":"45","text":"坠楼坠崖致死"},
            {"value":"46","text":"中毒致死"},
            {"value":"47","text":"爆炸致死"},
            {"value":"50","text":"社会安全事件致死"},
            {"value":"51","text":"打架斗殴致死"},
            {"value":"52","text":"校园伤害致死"},
            {"value":"53","text":"刑事案件致死"},
            {"value":"54","text":"火灾致死"},
            {"value":"60","text":"自然灾害致死"},
            {"value":"61","text":"山体滑坡致死"},
            {"value":"62","text":"泥石流致死"},
            {"value":"63","text":"洪水致死"},
            {"value":"64","text":"地震致死"},
            {"value":"65","text":"暴雨致死"},
            {"value":"66","text":"冰雹致死"},
            {"value":"67","text":"雪灾致死"},
            {"value":"68","text":"龙卷风致死"},
            {"value":"70","text":"因病死亡"},
            {"value":"71","text":"传染病致死"},
            {"value":"72","text":"猝死"},
            {"value":"79","text":"其他疾病致死"},
            {"value":"81","text":"自杀死亡"},
            {"value":"89","text":"其他原因死亡"}

        ],
        //考核类别码
        KHLBM:[
            {"value":"1","text":"平时考核"},
            {"value":"2","text":"年度考核"},
            {"value":"3","text":"特定考核"}
        ],
        //考核结果码
        KHJGM:[
            {"value":"1","text":"优秀"},
            {"value":"2","text":"优秀"},
            {"value":"3","text":"基本称职"},
            {"value":"4","text":"不称职"},
            {"value":"5","text":"不确定考核等级"}
        ],
        //考察（考核）类别码
        KCLBM:[
            {"value":"1","text":"平时考核"},
            {"value":"2","text":"年度考核"},
            {"value":"3","text":"特定考核"}
        ],
        //考察（考核）结果码
        KCJGM:[
            {"value":"1","text":"优秀"},
            {"value":"2","text":"优秀"},
            {"value":"3","text":"基本称职"},
            {"value":"4","text":"不称职"},
            {"value":"5","text":"不确定考核等级"}
        ],
        //考核工种码
        KHGZM:[
            {"value":"1","text":"机械加工类"},
            {"value":"2","text":"电工电器工程类"},
            {"value":"3","text":"建筑工程类"},
            {"value":"4","text":"仪器仪表工程类"},
            {"value":"5","text":"水暖通风工程类"},
            {"value":"6","text":"机动车驾驶类"},
            {"value":"7","text":"家具维修类"},
            {"value":"8","text":"宣传广告标本制作类"},
            {"value":"9","text":"餐饮服务类"},
            {"value":"10","text":"商贸服务类"},
            {"value":"11","text":"护理保健类"},
            {"value":"12","text":"花木养殖类"},
            {"value":"13","text":"其他"}
        ],
        //编制类别
        BZLB:[
            {"value":"10","text":"教学类"},
            {"value":"20","text":"行政类"},
            {"value":"30","text":"教辅类"},
            {"value":"40","text":"工勤类"},
            {"value":"50","text":"科研类"},
            {"value":"60","text":"校办企业类"},
            {"value":"70","text":"附设机构类"},
            {"value":"99","text":"其他类"}
        ],
        //编制异动
        BZYDM:[
            {"value":"1","text":"调至非教学岗位"},
            {"value":"2","text":"调至教学岗位"},
            {"value":"9","text":"其他"}
        ],
        //获奖类型
        HJLX:[
            {"value":"1","text":"集体"},
            {"value":"2","text":"个人综合"},
            {"value":"3","text":"个人单项"}
        ],
        //奖励方式
        JLFS:[
            {"value":"1","text":"奖状"},
            {"value":"2","text":"荣誉称号"},
            {"value":"3","text":"奖金"},
            {"value":"4","text":"实物"},
            {"value":"9","text":"其他"}
        ],
        //获奖类别
        HJLB:[
            {"value":"1","text":"学科获奖"},
            {"value":"2","text":"科技获奖"},
            {"value":"3","text":"文艺获奖"},
            {"value":"4","text":"工体育获奖"},
            {"value":"5","text":"综合获奖"},
            {"value":"6","text":"社会工作获奖"},
            {"value":"7","text":"公益事业获奖"},
            {"value":"9","text":"其他"}
        ],
        //处分名称
        CFMC:[
            {"value":"1","text":"警告"},
            {"value":"2","text":"严重警告"},
            {"value":"3","text":"记过"},
            {"value":"4","text":"留校察看"},
            {"value":"5","text":"开除学籍"},
            {"value":"6","text":"其他"}
        ],
        //学籍异动
        XJYD:[
            {"value":"01","text":"公派留学"},
            {"value":"02","text":"留级"},
            {"value":"03","text":"降级"},
            {"value":"04","text":"跳级"},
            {"value":"05","text":"试读"},
            {"value":"06","text":"延长年限"},
            {"value":"07","text":"试读通过"},
            {"value":"08","text":"回国复学"},
            {"value":"11","text":"休学"},
            {"value":"12","text":"复学"},
            {"value":"13","text":"停学"},
            {"value":"14","text":"保留入学资格"},
            {"value":"15","text":"恢复入学资格"},
            {"value":"16","text":"取消入学资格"},
            {"value":"17","text":"恢复学籍"},
            {"value":"18","text":"取消学籍"},
            {"value":"19","text":"保留学籍"},
            {"value":"21","text":"转学（转出）"},
            {"value":"22 1","text":"转学（转入）"},
            {"value":"23","text":"转专业"},
            {"value":"24","text":"专升本"},
            {"value":"25","text":"本转专"},
            {"value":"26","text":"转系"},
            {"value":"27","text":"硕转博"},
            {"value":"28","text":"博转硕"},
            {"value":"29","text":"转班级"},
            {"value":"31","text":"退学"},
            {"value":"42","text":"开除学籍"},
            {"value":"51","text":"死亡"},
            {"value":"61","text":"提前毕业"},
            {"value":"62","text":"结业"},
            {"value":"63","text":"肄业"},
            {"value":"64","text":"国内访学"},
            {"value":"65","text":"国内访学后返校"},
            {"value":"99","text":"其他"}
        ],
        //学籍异动原因
        YDYY:[
            {"value":"01","text":"成绩优秀"},
            {"value":"10","text":"疾病"},
            {"value":"11","text":"精神疾病"},
            {"value":"12","text":"传染疾病"},
            {"value":"19","text":"其他疾病"},
            {"value":"21","text":"自动退学"},
            {"value":"22","text":"成绩太差"},
            {"value":"23","text":"触犯刑法"},
            {"value":"24","text":"休学创业"},
            {"value":"25","text":"停学实践（求职）"},
            {"value":"26","text":"家长病重"},
            {"value":"27","text":"贫困"},
            {"value":"28","text":"非留学出国（境）"},
            {"value":"29","text":"自费出国退学"},
            {"value":"30","text":"自费留学"},
            {"value":"31","text":"休学期满未办理复学"},
            {"value":"32","text":"恶意欠缴学费"},
            {"value":"33","text":"超过最长学习期限未完成学业"},
            {"value":"34","text":"应征入伍"},
            {"value":"39","text":"其他原因退学"},
            {"value":"41","text":"溺水死亡"},
            {"value":"42","text":"交通事故致死"},
            {"value":"43","text":"拥挤踩踏致死"},
            {"value":"44","text":"房屋倒塌致死"},
            {"value":"45","text":"坠楼坠崖致死"},
            {"value":"46","text":"中毒致死"},
            {"value":"47","text":"爆炸致死"},
            {"value":"51","text":"打架斗殴致死"},
            {"value":"52","text":"校园伤害致死"},
            {"value":"53","text":"刑事案件致死"},
            {"value":"54","text":"火灾致死"},
            {"value":"61","text":"山体滑坡致死"},
            {"value":"62","text":"泥石流致死"},
            {"value":"63","text":"洪水致死"},
            {"value":"64","text":"地震致死"},
            {"value":"65","text":"暴雨致死"},
            {"value":"66","text":"冰雹致死"},
            {"value":"67","text":"雪灾致死"},
            {"value":"68","text":"龙卷风致死"},
            {"value":"70","text":"因病死亡"},
            {"value":"71","text":"传染病致死"},
            {"value":"72","text":"猝死"},
            {"value":"79","text":"其他疾病致死"},
            {"value":"81","text":"自杀死亡"},
            {"value":"89","text":"其他原因死亡"}
        ],
         //结束学业码
        JSXYM:[
            {"value":"1","text":"毕业"},
            {"value":"2","text":"结业"},
            {"value":"3","text":"未结业"},
            {"value":"4","text":"肄业"}
        ],
        //毕业去向码
        BYQXM:[
            {"value":"1","text":"本科"},
            {"value":"2","text":"高职（专科）"},
            {"value":"3","text":"职业高中（含中专、技校）"},
            {"value":"4","text":"职业初中"},
            {"value":"5","text":"普通高中"},
            {"value":"6","text":"普通初中"},
            {"value":"7","text":"就业"},
            {"value":"8","text":"参军"},
            {"value":"9","text":"出国"},
            {"value":"10","text":"赴港澳台"},
            {"value":"11","text":"待就业"},
            {"value":"12","text":"其他"}
        ],
         //入学方式
        RXFSM:[
            {"value":"1","text":"统一招生考试/普通入学"},
            {"value":"2","text":"保送"},
            {"value":"3","text":"民族班"},
            {"value":"4","text":"定向培养"},
            {"value":"5","text":"体育特招"},
            {"value":"6","text":"文艺特招"},
            {"value":"7","text":"学生干部保送"},
            {"value":"8","text":"考试推荐"},
            {"value":"9","text":"外校转入"},
            {"value":"10","text":"恢复入学资格"},
            {"value":"11","text":"预科班"},
            {"value":"12","text":"来华留学"},
            {"value":"13","text":"其他"}
        ],
		 //学生来源
        XSLYM:[
            {"value":"1","text":"研究生"},
            {"value":"2","text":"科技人员"},
            {"value":"3","text":"高校教师"},
            {"value":"4","text":"中学教师"},
            {"value":"5","text":"其他人员"},
            {"value":"6","text":"普通高校本专科/中等职业学校"},
            {"value":"7","text":"城镇应届"},
            {"value":"8","text":"农村应届"},
            {"value":"9","text":"城镇往届"},
            {"value":"10","text":"农村往届"},
            {"value":"11","text":"工人"},
            {"value":"12","text":"干部"},
            {"value":"13","text":"复退军人"},
            {"value":"8","text":"现役军人"},
            {"value":"9","text":"香港生"},
            {"value":"10","text":"澳门生"},
            {"value":"11","text":"台湾生"}
        ],
         //就读方式
        JDFSM:[
            {"value":"1","text":"走读"},
            {"value":"2","text":"住校"},
            {"value":"3","text":"借宿"},
            {"value":"4","text":"其他"}
        ],
         //评价结果码
        PJJGM:[
            {"value":"1","text":"优秀"},
            {"value":"2","text":"良好"},
            {"value":"3","text":"及格"},
            {"value":"4","text":"不及格"}
        ],
         //学生当前状态码
        XSDQZTM:[
            {"value":"1","text":"在读"},
            {"value":"2","text":"休学"},
            {"value":"3","text":"退学"},
            {"value":"4","text":"停学"},
            {"value":"5","text":"复学"},
            {"value":"6","text":"流失"},
            {"value":"7","text":"毕业"},
            {"value":"8","text":"结业"},
            {"value":"9","text":"肄业"},
            {"value":"10","text":"转学（转出）"},
            {"value":"11","text":"死亡"},
            {"value":"12","text":"保留入学资格"},
            {"value":"3","text":"公派出国"},
            {"value":"4","text":"开除"},
            {"value":"5","text":"下落不明"},
            {"value":"6","text":"其他"}
        ],
        //学生类别码
        XSLBM:[
            {"value":"1","text":"学前教育"},
            {"value":"2","text":"幼儿"},
            {"value":"3","text":"小学生"},
            {"value":"4","text":"普通小学生学"},
            {"value":"5","text":"成人小学生"},
            {"value":"6","text":"初中生"},
            {"value":"7","text":"普通初中学生"},
            {"value":"8","text":"职业初中学生"},
            {"value":"9","text":"成人初中学生"},
            {"value":"10","text":"普通高中学生"},
            {"value":"11","text":"成人高中学生"}
        ],
        //中小学编制类别代码
        ZXXBZLB:[
            {"value":"1","text":"专任教师"},
            {"value":"2","text":"行政人员"},
            {"value":"3","text":"教辅人员"},
            {"value":"4","text":"工勤人员"},
            {"value":"5","text":"校办企业职工"},
            {"value":"6","text":"代课教师"},
            {"value":"7","text":"兼任（职）教师"},
            {"value":"9","text":"其他"}
        ],
        //婚姻状况代码
        HYZKM:[
            {"value":"10","text":"未婚"},
            {"value":"20","text":"已婚"},
            {"value":"21","text":"初婚"},
            {"value":"22","text":"再婚"},
            {"value":"23","text":"复婚"},
            {"value":"30","text":"丧偶"},
            {"value":"40","text":"离婚"},
            {"value":"90","text":"未说明"}
        ],
        //从业状况代码
        CYZKM:[
            {"value":"11","text":"国家公务员"},
            {"value":"13","text":"专业技术人员"},
            {"value":"17","text":"职员"},
            {"value":"21","text":"企业管理人员"},
            {"value":"24","text":"工人"},
            {"value":"27","text":"农民"},
            {"value":"31","text":"学生"},
            {"value":"37","text":"现役军人"},
            {"value":"51","text":"自由职业者"},
            {"value":"54","text":"个体经营者"},
            {"value":"70","text":"无业人员"},
            {"value":"80","text":"退（离）休人员"},
            {"value":"90","text":"其他"}
        ],
        //家庭类别代码
        JTLBM:[
            {"value":"1","text":"双亲健全"},
            {"value":"2","text":"孤儿"},
            {"value":"3","text":"单亲（父母一方去世）"},
            {"value":"4","text":"父母离异"},
            {"value":"5","text":"双亲有残疾"},
            {"value":"6","text":"本人残疾"},
            {"value":"7","text":"军烈属或优抚对象"},
            {"value":"8","text":"重病"},
            {"value":"9","text":"五保户"}
        ],
        //困难程度
        KNCDM:[
            {"value":"1","text":"特别困难"},
            {"value":"2","text":"一般困难"},
            {"value":"3","text":"困难"},
            {"value":"4","text":"不困难"}
        ],
        //困难原因
        KNYYM:[
            {"value":"1","text":"自然灾害"},
            {"value":"2","text":"突发意外"},
            {"value":"3","text":"家庭成员病残"},
            {"value":"4","text":"家长失业"},
            {"value":"9","text":"其他"}
        ],
        //户口类别代码
        HKLBM:[
        	{"value":"0","text":"未落常住户口"},
            {"value":"1","text":"非农业家庭户口"},
            {"value":"2","text":"农业家庭户口"},
            {"value":"3","text":"非农业集体户口"},
            {"value":"4","text":"农业集体户口"},
            {"value":"5","text":"自理口粮户口"},
            {"value":"6","text":"寄住户口"},
            {"value":"7","text":"暂住户口"},
            {"value":"8","text":"其他户口"}
        ],
        //奖励名称代码
        JLMCM:[
            {"value":"1","text":"记一等功"},
            {"value":"2","text":"记二等功"},
            {"value":"3","text":"记三等功"},
            {"value":"4","text":"嘉奖"},
            {"value":"5","text":"授予荣誉称号"},
            {"value":"6","text":"记功"},
            {"value":"7","text":"记大功"},
            {"value":"8","text":"晋级"},
            {"value":"9","text":"通令嘉奖"},
            {"value":"10","text":"授予荣誉称号"},
            {"value":"11","text":"国家技术发明奖"},
            {"value":"12","text":"国家自然科学奖"},
            {"value":"13","text":"国家科学技术进步奖"},
            {"value":"14","text":"国家最高科学技术奖"},
            {"value":"15","text":"中华人民共和国国际科学技术合作奖"},
            {"value":"16","text":"省(自治区、直辖市、特别行政区)科学技术奖"},
            {"value":"17","text":"社会力量设立科学技术奖"},
            {"value":"18","text":"国家教学成果奖"},
            {"value":"19","text":"国际和国外奖励"},
            {"value":"20","text":"其他奖"}
        ],
        //荣誉称号代码
        RYCHM:[
        	{"value":"0","text":"特级劳动模范"},
            {"value":"1","text":"劳动模范"},
            {"value":"2","text":"劳动英雄"},
            {"value":"3","text":"先进工作者"},
            {"value":"4","text":"优秀共产党员"},
            {"value":"5","text":"优秀工会工作者"},
            {"value":"6","text":"优秀工会积极分子"},
            {"value":"7","text":"技术协作能手"},
            {"value":"8","text":"新长征突击手"},
            {"value":"9","text":"优秀共青团员干部"},
            {"value":"10","text":"三八红旗手"},
            {"value":"11","text":"三好学生"},
            {"value":"12","text":"优秀毕业生"},
            {"value":"13","text":"优秀共青团员"},
            {"value":"14","text":"优秀学生干部"},
            {"value":"15","text":"十佳少先队辅导员"},
            {"value":"16","text":"青年岗位能手"},
            {"value":"17","text":"杰出（优秀）青年卫士"},
            {"value":"18","text":"十大杰出青年"},
            {"value":"19","text":"各族青年团结进步杰出（优秀）奖"},
            {"value":"20","text":"农村优秀人才"},
            {"value":"21","text":"杰出青年农民"},
            {"value":"22","text":"农村青年创业致富带头人"},
            {"value":"23","text":"杰出（优秀）进城务工青年"},
            {"value":"24","text":"杰出（优秀）青年外事工作者"},
            {"value":"25","text":"青年科学家奖"},
            {"value":"26","text":"青年科技创新奖"},
            {"value":"27","text":"五四新闻奖"},
            {"value":"28","text":"未成年人保护杰出（优秀）公民"},
            {"value":"29","text":"留学回国人民成就奖"},
            {"value":"30","text":"全国留学回国人员先进个人"},
            {"value":"31","text":"民族团结进步模范"},
            {"value":"32","text":"十大农民女状元"},
            {"value":"33","text":"中国十大女杰"},
            {"value":"34","text":"“双学双比”先进女能手"},
            {"value":"35","text":"“双学双比”活动先进工作者"},
            {"value":"36","text":"十大绿化女壮元"},
            {"value":"37","text":"巾帼创业带头人"},
            {"value":"38","text":"“巾帼建功”标兵"},
            {"value":"39","text":"巾帼文明示范岗"},
            {"value":"40","text":"“不让毒品进我家”先进个人"},
            {"value":"41","text":"“不让毒品进我家”活动先进工作者"},
            {"value":"42","text":"维护妇女儿童权益先进个人"},
            {"value":"43","text":"先进工作者"},
            {"value":"44","text":"优秀党务工作者"},
            {"value":"45","text":"模范公务员"},
            {"value":"46","text":"人民满意的公务员"},
            {"value":"47","text":"有突击贡献的中青年专家"},
            {"value":"48","text":"政府特殊津贴获得者"},
            {"value":"49","text":"杰出专业技术人才"},
            {"value":"50","text":"模范教师"},
            {"value":"51","text":"优秀教师"},
            {"value":"52","text":"优秀教育工作者"},
            {"value":"53","text":"中华技能大奖"},
            {"value":"54","text":"技术能手"}
        ],
        //奖励方式代码
        JLFSM:[
            {"value":"1","text":"记一等功"},
            {"value":"2","text":"记二等功"},
            {"value":"3","text":"记三等功"},
            {"value":"4","text":"嘉奖"},
            {"value":"5","text":"授予荣誉称号"},
            {"value":"6","text":"记功"},
            {"value":"7","text":"记大功"},
            {"value":"8","text":"晋级"},
            {"value":"9","text":"通令嘉奖"},
            {"value":"10","text":"授予荣誉称号"},
            {"value":"11","text":"国家技术发明奖"},
            {"value":"12","text":"国家自然科学奖"},
            {"value":"13","text":"国家科学技术进步奖"},
            {"value":"14","text":"国家最高科学技术奖"},
            {"value":"15","text":"中华人民共和国国际科学技术合作奖"},
            {"value":"16","text":"省(自治区、直辖市、特别行政区)科学技术奖"},
            {"value":"17","text":"社会力量设立科学技术奖"},
            {"value":"18","text":"国家教学成果奖"},
            {"value":"19","text":"国际和国外奖励"},
            {"value":"20","text":"其他奖"}
        ],
        // 纪律处分代码
        JLCFM:[
            {"value":"20","text":"警告"},
            {"value":"22","text":"记过"},
            {"value":"23","text":"记大过"},
            {"value":"24","text":"降级"},
            {"value":"27","text":"撤职"},
            {"value":"28","text":"留用察看"},
            {"value":"29","text":"开除"}
        ],
        // 学习方式代码
        XXFSM:[
            {"value":"1","text":"全脱产(离岗)"},
            {"value":"2","text":"半脱产(半离岗)"},
            {"value":"3","text":"不脱产(不离岗)"}
        ],
        // 学习形式代码
        XXXSM:[
            {"value":"01","text":"普通高等学校"},
            {"value":"02","text":"高等教育自学考试"},
            {"value":"03","text":"夜大学"},
            {"value":"04","text":"职工大学"},
            {"value":"05","text":"电视大学"},
            {"value":"06","text":"业余大学"},
            {"value":"07","text":"函授"},
            {"value":"08","text":"研修班"},
            {"value":"09","text":"高等学校进修"},
            {"value":"10","text":"党校"},
            {"value":"11","text":"社会主义学院"},
            {"value":"15","text":"培训"},
            {"value":"99","text":"其他"},
        ],
        // 外国语种代码
        WGYZM:[
            {"value":"zh","text":"汉语(中文)"},
            {"value":"aa","text":"阿法尔语"},
            {"value":"ab","text":"阿布哈兹语考试"},
            {"value":"af","text":"阿非利堪斯语"},
            {"value":"am","text":"阿姆哈拉语"},
            {"value":"ar","text":"阿拉伯语"},
            {"value":"as","text":"阿萨姆语"},
            {"value":"ay","text":"艾马拉语"},
            {"value":"az","text":"阿塞拜疆语"},
            {"value":"ba","text":"巴什基尔语"},
            {"value":"be","text":"白俄罗斯语"},
            {"value":"bg","text":"保加利亚语"},
            {"value":"bh","text":"比哈尔语"},
            {"value":"bi","text":"比斯拉玛语"},
            {"value":"bn","text":"孟加拉语"},
            {"value":"bo","text":"藏语考试"},
            {"value":"br","text":"布列塔尼语"},
            {"value":"ca","text":"加泰隆语"},
            {"value":"co","text":"科西嘉语"},
            {"value":"cs","text":"捷克语"},
            {"value":"cy","text":"威尔士语"},
            {"value":"da","text":"丹麦语"},
            {"value":"de","text":"德语"},
            {"value":"dz","text":"不丹语"},
            {"value":"el","text":"希腊语"},
            {"value":"en","text":"英语"},
            {"value":"eo","text":"世界语"},
            {"value":"es","text":"西班牙语"},
            {"value":"et","text":"爱沙尼亚语考试"},
            {"value":"eu","text":"巴斯克语"},
            {"value":"fa","text":"波斯语"},
            {"value":"fi","text":"芬兰语"},
            {"value":"fj","text":"斐济语"},
            {"value":"fo","text":"法罗斯语"},
            {"value":"fr","text":"法语"},
            {"value":"fy","text":"弗里西亚语"},
            {"value":"ga","text":"爱尔兰语"},
            {"value":"gd","text":"苏格兰语"},
            {"value":"gl","text":"加利西亚语"},
            {"value":"gn","text":"瓜拉尼语"},
            {"value":"gu","text":"古吉拉特语"},
            {"value":"ha","text":"豪萨语"},
            {"value":"hi","text":"印地语"},
            {"value":"hr","text":"克罗地亚语"},
            {"value":"hu","text":"匈牙利语"},
            {"value":"hy","text":"亚美尼亚语"},
            {"value":"ia","text":"国际语 A"},
            {"value":"ie","text":"国际语 E"},
            {"value":"ik","text":"依努庇克语"},
            {"value":"in","text":"印尼语"},
            {"value":"is","text":"冰岛语"},
            {"value":"it","text":"意大利语"},
            {"value":"iw","text":"希伯来语"},
            {"value":"ja","text":"日语"},
            {"value":"ji","text":"依地语"},
            {"value":"jv","text":"爪哇语"},
            {"value":"ka","text":"格鲁吉亚语"},
            {"value":"kk","text":"哈萨克语"},
            {"value":"kl","text":"格陵兰语"},
            {"value":"km","text":"柬埔寨语"},
            {"value":"kn","text":"坎纳达语"},
            {"value":"ko","text":"朝鲜语"},
            {"value":"ks","text":"克什米尔语"},
            {"value":"ku","text":"库尔德语"},
            {"value":"ky","text":"吉尔吉斯语"},
            {"value":"la","text":"拉丁语"},
            {"value":"ln","text":"林加拉语"},
            {"value":"lo","text":"老挝语"},
            {"value":"lt","text":"立陶宛语"},
            {"value":"lv","text":"拉脱维亚语"},
            {"value":"mg","text":"马达加斯加语"},
            {"value":"mi","text":"毛利语"},
            {"value":"mk","text":"马其顿语"},
            {"value":"ml","text":"马拉亚拉姆语"},
            {"value":"mn","text":"蒙古语"},
            {"value":"mo","text":"摩尔达维亚语"},
            {"value":"mr","text":"马拉提语"},
            {"value":"ms","text":"马来语"},
            {"value":"mt","text":"马耳他语"},
            {"value":"my","text":"缅甸语"},
            {"value":"na","text":"瑙鲁语"},
            {"value":"ne","text":"尼泊尔语"},
            {"value":"nl","text":"芬兰语"},
            {"value":"no","text":"挪威语"},
            {"value":"oc","text":"奥克西唐语"},
            {"value":"om","text":"阿芳·奥洛莫语"},
            {"value":"or","text":"奥利亚语"},
            {"value":"pa","text":"旁遮普语"},
            {"value":"pl","text":"波兰语"},
            {"value":"ps","text":"普什图语"},
            {"value":"pt","text":"葡萄牙语"},
            {"value":"qu","text":"凯楚亚语"},
            {"value":"rm","text":"利托－罗曼语"},
            {"value":"rn","text":"基隆迪语"},
            {"value":"ro","text":"罗马尼亚语"},
            {"value":"ru","text":"俄语"},
            {"value":"rw","text":"基尼阿万达语"},
            {"value":"sa","text":"梵语"},
            {"value":"sd","text":"信德语"},
            {"value":"sg","text":"桑戈语"},
            {"value":"sh","text":"塞尔维亚－克罗地亚语"},
            {"value":"si","text":"僧加罗语"},
            {"value":"sk","text":"斯洛伐克语"},
            {"value":"sl","text":"斯洛文尼亚语"},
            {"value":"sm","text":"萨摩亚语"},
            {"value":"sn","text":"绍纳语"},
            {"value":"so","text":"索马里语"},
            {"value":"sq","text":"阿尔巴尼亚语"},
            {"value":"sr","text":"塞尔维亚语"},
            {"value":"ss","text":"塞斯瓦替语"},
            {"value":"st","text":"塞索托语"},
            {"value":"su","text":"巽他语"},
            {"value":"sv","text":"瑞典语"},
            {"value":"sw","text":"斯瓦希里语"},
            {"value":"ta","text":"泰米尔语"},
            {"value":"te","text":"泰卢固语"},
            {"value":"tg","text":"塔吉克语"},
            {"value":"th","text":"傣语"},
            {"value":"ti","text":"提格里尼亚语"},
            {"value":"tk","text":"土库曼语"},
            {"value":"tl","text":"他加禄语"},
            {"value":"tn","text":"塞茨瓦纳语"},
            {"value":"to","text":"汤加语"},
            {"value":"tr","text":"土耳其语"},
            {"value":"ts","text":"宗加语"},
            {"value":"tt","text":"塔塔尔语"},
            {"value":"tw","text":"特威语"},
            {"value":"ug","text":"维吾尔语"},
            {"value":"uk","text":"乌克兰语"},
            {"value":"ur","text":"乌尔都语"},
            {"value":"uz","text":"乌兹别克语"},
            {"value":"vi","text":"越南语"},
            {"value":"vo","text":"沃拉普克语"},
            {"value":"wo","text":"沃洛夫语"},
            {"value":"xh","text":"科萨语"},
            {"value":"yo","text":"约鲁巴语"},
            {"value":"za","text":"壮语"},
            {"value":"zu","text":"祖鲁语"},
            {"value":"zz","text":"其他语言 "}
        ],
        // 熟练程度代码
        SLCDM:[
            {"value":"1","text":"精通"},
            {"value":"2","text":"熟练"},
            {"value":"3","text":"良好"},
            {"value":"4","text":"一般"}
        ],
        //资格种类码
        ZGZLM:[
            {"value":"1","text":"幼儿园教师资格"},
            {"value":"2","text":"小学教师资格"},
            {"value":"3","text":"初级中学教师资格"},
            {"value":"4","text":"高级中学教师资格"},
            {"value":"5","text":"中等职业学校教师资格"},
            {"value":"6","text":"中等职业学校实习指导教师资格"},
            {"value":"7","text":"高等学校教师资格"}
        ],
        // 中国语种代码
        ZGYZM:[
            {"value":"211","text":"汉语（中文）"},
            {"value":"212","text":"傣语"},
            {"value":"215","text":"藏语"},
            {"value":"217","text":"朝鲜语"},
            {"value":"222","text":"蒙古语"},
            {"value":"223","text":"维吾尔语"},
            {"value":"224","text":"壮语"},
            {"value":"518","text":"满语"},
            {"value":"580","text":"苗语"},
            {"value":"061","text":"俄语"},
            {"value":"536","text":"阿昌语"},
            {"value":"111","text":"塔吉克语"},
            {"value":"537","text":"独龙语"},
            {"value":"161","text":"塔塔尔语"},
            {"value":"538","text":"基诺语"},
            {"value":"162","text":"柯尔克孜语"},
            {"value":"539","text":"珞巴语"},
            {"value":"163","text":"哈萨克语"},
            {"value":"540","text":"门巴语"},
            {"value":"168","text":"乌孜别克语"},
            {"value":"541","text":"怒语"},
            {"value":"542","text":"普米语"},
            {"value":"543","text":"羌语"},
            {"value":"544","text":"土家语"},
            {"value":"548","text":"景颇语"},
            {"value":"551","text":"白语"},
            {"value":"552","text":"哈尼语"},
            {"value":"553","text":"拉祜语"},
            {"value":"501","text":"裕固语"},
            {"value":"554","text":"傈僳语"},
            {"value":"506","text":"保安语"},
            {"value":"555","text":"纳西语"},
            {"value":"507","text":"达斡尔语"},
            {"value":"556","text":"彝语"},
            {"value":"508","text":"东乡语"},
            {"value":"563","text":"黎语"},
            {"value":"509","text":"土语"},
            {"value":"567","text":"侗语"},
            {"value":"513","text":"鄂伦春语"},
            {"value":"568","text":"仫佬语"},
            {"value":"514","text":"鄂温克语"},
            {"value":"569","text":"毛难语"},
            {"value":"517","text":"赫哲语"},
            {"value":"570","text":"水语"},
            {"value":"574","text":"布依语"},
            {"value":"519","text":"锡伯语"},
            {"value":"524","text":"撒拉语"},
            {"value":"584","text":"崩龙语"},
            {"value":"531","text":"瑶语"},
            {"value":"585","text":"布朗语"},
            {"value":"532","text":"仡佬语"},
            {"value":"586","text":"佤语"},
            {"value":"533","text":"京语"},
            {"value":"590","text":"高山语"}
        ],
        //普通话水平等级代码
        PTHSPDJ:[
            {"value":"1","text":" 一级甲等"},
            {"value":"2","text":"一级乙等"},
            {"value":"3","text":" 二级甲等"},
            {"value":"4","text":" 二级乙等"},
            {"value":"5","text":"三级甲等"},
            {"value":"6","text":" 三级乙等"}
        ],
        //教师资格种类代码
        JSZGZL:[
        	{"value":"1","text":"幼儿园教师资格"},
        	{"value":"2","text":"小学教师资格"},
        	{"value":"3","text":"初级中学教师资格"},
        	{"value":"4","text":"高级中学教师资格"},
        	{"value":"5","text":"中等职业学校教师资格"},
        	{"value":"6","text":"中等职业学校实习指导教师资格"},
        	{"value":"7","text":"高等学校教师资格"}
        ],
		//办学类型代码
        BXLXM:[
        	{"value":"1","text":"学前教育"},
        	{"value":"2","text":"初等教育"},
        	{"value":"3","text":"中等教育"},
        	{"value":"4","text":"高等教育"},
        	{"value":"5","text":"特殊教育"},
        	{"value":"6","text":"其他教育"}
        ],
        //学校办别代码
        XXBBM:[
        	{"value":"10","text":"普通中小学/职业中学"},
        	{"value":"11","text":"教育部门和集体办"},
        	{"value":"12","text":"社会力量办"},
        	{"value":"19","text":"其他部门办"},
        	{"value":"20","text":"其他中等职业学校"},
        	{"value":"21","text":"公办"},
        	{"value":"22","text":"民办"},
        	{"value":"23","text":"民办公助"},
        	{"value":"29","text":"其他"},
        ]
}
    window.CODE = CODE;

})